@url = "http://localhost:3000/"
 
GET http://localhost:3000/flight HTTP/1.1

###
GET http://localhost:3000/flight/0eb53340-ed8f-4589-8902-880652f63a83 HTTP/1.1

###

POST http://localhost:3000/flight HTTP/1.1
Content-Type: application/json

{
    "title": "flight to Stealth",
    "time": "7am",
    "price": "100000",
    "date":"29-02-2024"
}

###

PUT http://localhost:3000/flight/0eb53340-ed8f-4589-8902-880652f63a83 HTTP/1.1
Content-Type: application/json

{
    "title": "flight to may",
    "time": "8am",
    "price": "60000",
    "date":"23-08-2022"
}

###

DELETE http://localhost:3000/flight/3d7defda-8523-4ac9-98a3-e5425aa5b075 HTTP/1.1
